-- Auto-generated from schema-map-postgres.yaml (map@sha1:F0EE237771FBA8DD7C4E886FF276F91A862C3718)
-- engine: postgres
-- table:  data_retention_policies

CREATE TABLE IF NOT EXISTS data_retention_policies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_table VARCHAR(64) NOT NULL,
  field_name   VARCHAR(64) NULL,
  action TEXT NOT NULL,                         -- 'delete','anonymize','hash','truncate'
  keep_for VARCHAR(64) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  notes TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_drp_action CHECK (action IN ('delete','anonymize','hash','truncate')),
  CONSTRAINT uq_drp_entity_scope UNIQUE (entity_table, field_name, action, keep_for)
);
